name: black
on: [push, pull_request]
jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
      - run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/psf/black
      - run: |
          black --check --verbose .
